import type { Metadata } from "next";
import {  Vazirmatn } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const Vazir = Vazirmatn({subsets:['arabic']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Vazir.className}>{children}</body>
    </html>
  );
}
